### ISSUE TITLE
[Question] Support with relation model

### ISSUE THREAD

**Issue by alimustofa** [estate/bookshelf-paranoia#10]
Hi @alanhoff, 

I have a problem when try to soft delete with related model. Is it package support for related model?
Below is my model.

Question Model
```
'use strict';

const Answer = require('./Answer');

bookshelf.plugin(require('bookshelf-paranoia'));

module.exports = bookshelf.Model.extend({
    tableName: 'questions',
    hasTimestamps: true,
    sofDelete: true,

    answer: function() {
        return this.hasMany(Question, 'question');
    },
});
```

Answer Model
```
'use strict';

const Question = require('./Question');

bookshelf.plugin(require('bookshelf-paranoia'));

module.exports = bookshelf.Model.extend({
    tableName: 'answers',
    hasTimestamps: true,
    sofDelete: true,

    question: function() {
        return this.belongsTo(Question, 'question');
    },
});
```

So, I want when the question was deleted, automatically answers are delete too.

Sorry for my bad english :)
Thanks!

**Comment by bsiddiqui** [comment]
@alimustofa sorry for the delayed response. We do not currently support deleting related models.

It would be fairly easy for you to do that. Checkout this issue to see some suggestions https://github.com/tgriesser/bookshelf/issues/135
