### ISSUE TITLE
Works on some models but not others

### ISSUE THREAD

**Issue by l-c** [estate/bookshelf-paranoia#26]
I am able to get softDelete to work according to the documentation on most tables, but on my users table, where I hash passwords, this doesn't seem to work:

`var User = bookshelf.Model.extend({
  tableName: 'users',
  hasTimestamps: true,
  softDelete: true,

  initialize: function() {
    this.on('saving', this.hashPassword, this);
  },

  hashPassword: function(model, attrs, options) {
    var password = options.patch ? attrs.password : model.get('password');
    if (!password) { return; }
    return new Promise(function(resolve, reject) {
      bcrypt.genSalt(10, function(err, salt) {
        bcrypt.hash(password, salt, null, function(err, hash) {
          if (options.patch) {
            attrs.password = hash;
          }
          model.set('password', hash);
          resolve();
        });
      });
    });
  },`

**When I remove the initialize and hashPassword functions, everything works as intended.**

**Comment by yusufsyaifudin** [comment]
I have same problem, and as l-c's said, if initialized function is removed it works well

**Comment by bsiddiqui** [comment]
Looks like you maybe have an issue because you're overriding the prototype's initialize function. You can fix this by calling `modelPrototype.initialize.call(this)`.

See an example of how we do this: https://github.com/estate/bookshelf-paranoia/blob/master/index.js#L69
