### ISSUE TITLE
Using require: true on destroy issues CustomError: No Rows Deleted

### ISSUE THREAD

**Issue by jccguimaraes** [estate/bookshelf-paranoia#28]
Hi,

I am using `{require: true}` as the `options` passed to **destroy** method and works fine without the plugin. As is supposed to delete only if exists.

With the plugin I am having:

```sh
{ CustomError: No Rows Deleted
    at Promise.resolve.then.then.then (<MY_MODULE_PATH>/node_modules/bookshelf-paranoia/index.js:149:19)
```

It soft deletes all relations except the current model that I invoked the destroy.

It is supposed to not support `{require: true}`? If so, it is a bummer to remove from all current models.

**Comment by bsiddiqui** [comment]
That looks like the proper error. If you use `{ require: true }` when calling destroy, the model will throw an error if the model is not destroyed. See [Bookshelf's documentation](http://bookshelfjs.org/#Model-instance-destroy)

**Comment by jccguimaraes** [comment]
Fair enough. Hoping that the plugin would ignore or or bypass the require prop.

thanks for clearing that out

**Comment by bsiddiqui** [comment]
@jccguimaraes I think that would be unexpected for a lot of people since the expectation without the plugin would be that you'd get the error when calling destroy. It feels like the risk of silencing an error someone might be expecting is high.

**Comment by jccguimaraes** [comment]
thanks @bsiddiqui!

**Comment by davidgf** [comment]
@bsiddiqui I do agree that a `NoRowsDeleted` error must be thrown if `require` is `true` and no row was soft deleted, but I think I've spotted an error. I'm using MySQL along with the [mysql2 driver](https://www.npmjs.com/package/mysql2), and when I soft delete a row [the response here](https://github.com/bsiddiqui/bookshelf-paranoia/blob/master/index.js#L170) is simply `1`, which doesn't pass the [isEmpty check](https://github.com/bsiddiqui/bookshelf-paranoia/blob/master/index.js#L173) and it throws an error, even though the row was effectively (soft) deleted.

**Comment by davidgf** [comment]
I'm submitting a PR, as I think I've found an issue
