### ISSUE TITLE
Wrong query building when fetching with `withRelated`

### ISSUE THREAD

**Issue by gabmontes** [estate/bookshelf-paranoia#4]
I came across this issue running queries with option `withRelated` and polymorphic props. The queries executed against the db end up having their "deleted_at" checks mixed up and break.

In my scenario there are 3 entities: `girls`, `boys`, `parents`. `parents` have a `child` prop that can either be a girl or a boy.

```js
const Boy = bookshelf.Model.extend({
  tableName: 'boys',
  softDelete: true
})
const Girl = bookshelf.Model.extend({
  tableName: 'girls',
  softDelete: true
})
const Parent = bookshelf.Model.extend({
  tableName: 'parents',
  child () {
    return this.morphTo('child', Boy, Girl)
  },
  softDelete: true
})
```

Then, have to create a boy, a parent having that boy, a girl and a parent having that girl:

```js
const waterfall = require('promise-waterfall')

function createBoy() {
  return Boy.forge().save().then(function (child) {
    return child.id
  })
}
function createGirl() {
  return Girl.forge().save().then(function (child) {
    return child.id
  })
}
function createParent() {
  return Parent.forge().save().then(function (parent) {
    return parent.id
  })
}
function setChild(parentId, childId, type) {
  return Parent.forge({
    id: parentId
  }).save({
    child_id: childId,
    child_type: type
  })
}

const tasks = waterfall([
  function () {
    return createBoy()
  },
  function (childId) {
    return createParent().then(function (parentId) {
      return setChild(parentId, childId, 'boys')
    })
  },
  function () {
    return createGirl()
  },
  function (parentBoyId) {
    return createParent().then(function (parentId) {
      return setChild(parentId, parentBoyId, 'girls')
    })
  }
])
```

Finally, fetch all parents with their children:

```js
tasks.then(function () {
  return Parent.fetchAll({
    withRelated: ['child'],
    debug: true
  })
})
```

The output is:

```
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [],
  sql: 'select "parents".* from "parents" where "parents"."deleted_at" is null and "parents"."deleted_at" is null' }
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [ '1' ],
  sql: 'select "boys".* from "boys" where "id" in (?)' }
{ method: 'select',
  options: {},
  timeout: false,
  bindings: [ '1' ],
  sql: 'select "girls".* from "girls" where "id" in (?) and "boys"."deleted_at" is null and "girls"."deleted_at" is null' }
Err: error: select "girls".* from "girls" where "id" in ($1) and "boys"."deleted_at" is null and "girls"."deleted_at" is null - missing FROM-clause entry for table «boys»
```

As can be seen in the logs, the `and "boys"."deleted_at" is null` in the last query (girls) is wrong and breaking. In addition, that condition is missing from the second query (boys).

Tested using:
- bookshelf@0.9.5
- bookshelf-paranoia@0.7.0
- knex@0.11.5

Will really appreciate any help with the issue. Thanks!!!

PS: You can see the whole test file at [test-bookshelf-paranoia.js](https://gist.github.com/gabmontes/3f7723a36fc3bec622252fd470da15fe)

**Comment by alanhoff** [comment]
Hello @gabmontes and thanks for the reporting. This seems to be related with how bookshelf handles morph relations. I'll do a better research during the week.

**Comment by kamronbatman** [comment]
Any updates on this?

Thanks!

**Comment by bsiddiqui** [comment]
Unfortunately we haven't had a chance to look into it yet - we'll do our best to do so in the next week or so. PR's welcome!

**Comment by alanhoff** [comment]
@gabmontes @kamronbatman sorry for the delay was a tricky one to debug. Morph relations should be working with `v0.8.0`, let me know if everything is ok :-)
