### ISSUE TITLE
enhancement: allow updating other fields on model during soft delete

### ISSUE THREAD

**Issue by jamesdixon** [estate/bookshelf-paranoia#5]
Hi, another great plugin from your team!

In many cases when I do a soft delete, I also set an `active` flag to `false` to deactivate the model. So for example, I have an `account` model which contains an `active` and `deleted_at` column. If I soft delete it, I'd also like to be able to deactivate that account rather than having to always ensure that when I'm specifying the state of `deleted_at` when I'm doing a query that involves `active`. 

Is this something that you could see as being valuable?

Thanks!
James

**Comment by alanhoff** [comment]
Hey @jamesdixon sorry for the delay. You could probably add a listener to the `destroying` event and update your model accordingly:

```javascript
this.on('destroyed', (model, options) => {
   if (options.softDelete) {
      // Should update `active` now
   }
})
```

**Comment by alanhoff** [comment]
@jamesdixon feel free to reopen this issue :-)
